
notify = ["/Users/ajitkrishna/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]
model = "gpt-5.5"
model_reasoning_effort = "xhigh"

[marketplaces.openai-bundled]
last_updated = "2026-06-19T22:26:29Z"
source_type = "local"
source = "/Users/ajitkrishna/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-06-19T21:07:40Z"
source_type = "local"
source = "/Users/ajitkrishna/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."build-macos-apps@openai-curated"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."chrome@openai-bundled"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[projects."/Users/ajitkrishna/Library/com.pieces.os"]
trust_level = "trusted"

[projects."/Users/ajitkrishna/Documents/Codex/2026-05-17/hi"]
trust_level = "trusted"

[projects."/Users/ajitkrishna/Documents/everything-ajit/programming/sonder"]
trust_level = "trusted"

[projects."/Users/ajitkrishna/.dotfiles"]
trust_level = "trusted"

[desktop]
ambient-suggestions-enabled = true
composerEnterBehavior = "cmdIfMultiline"
preventSleepWhileRunning = true
keepRemoteControlAwakeWhilePluggedIn = true
git-always-force-push = false
conversationDetailMode = "STEPS_COMMANDS"

[desktop.open-in-target-preferences]
global = "zed"

[features]
js_repl = false

[mcp_servers.node_repl]
args = []
command = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/Codex.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/ajitkrishna/.codex"
CODEX_HOME = "/Users/ajitkrishna/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "feca4d852d7d18eab5e217b18c8c80099fe667c330e836640fd7a48f362de525"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.616.32156"
CODEX_CLI_PATH = "/Applications/Codex.app/Contents/Resources/codex"

[tui.model_availability_nux]
"gpt-5.5" = 4
